# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Build_Site

jobs:
  build:
    runs-on: macOS-latest
    steps:

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install system level dependencies
        run: brew install pandoc

      - name: Cache Renv packages
      - uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
          ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build site
        run: |
          R -e 'rmarkdown::render_site()'

