on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build_Site

jobs:
  build:
    env:
      RENV_PATHS_ROOT: ~/Library/Application Support/renv
    runs-on: macOS-latest
    steps:

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install system level dependencies
        run: brew install pandoc

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build site
        run: |
          R -e 'rmarkdown::render_site()'

